{
 "title": "Vikunja Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Vikunja User Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "vikunja_user_count{instance=\"vikunja-backend.vikunja-app.svc.cluster.local:3456\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Vikunja Task Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "vikunja_task_count{instance=\"vikunja-backend.vikunja-app.svc.cluster.local:3456\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vikunja Project Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "vikunja_project_count{instance=\"vikunja-backend.vikunja-app.svc.cluster.local:3456\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vikunja Active Users",
   "type": "timeseries",
   "description": "Dashboard to populate Vikunja app metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "vikunja_active_users{instance=\"vikunja-backend.vikunja-app.svc.cluster.local:3456\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  }
 ]
}